FROM rust:1.97-alpine3.23 AS build
WORKDIR /app

RUN apk add protoc

COPY . .

ARG SQLX_OFFLINE=true
RUN cargo build --release

FROM scratch

COPY --from=build /app/target/release/music-catalog .
COPY migrations migrations
COPY config config

EXPOSE 8080

CMD ["./music-catalog"]
