FROM rust:1.97-alpine3.23 AS build
WORKDIR /app

RUN apk add protoc protobuf-dev

COPY . .

ARG SQLX_OFFLINE=true
RUN cargo build

FROM scratch

COPY --from=build /app/target/debug/music-catalog .
COPY migrations migrations
COPY config config

CMD ["./music-catalog"]