[postgres]
host = "postgres"
port = 5432
user = "user"
password = "pg-tracks-db"
database = "tracks-db"

[streaming]
play_token_key = "some long base64 key"

[rustfs]
access_key = "rustfsadmin"
secret_key = "rustfsadmin"
endpoint_url="http://rustfs:9000"
region="eu-west-1"
assets_bucket = "assets"