syntax = "proto3";

package categories;

service Categories {
    rpc CreateCategory(CreateCategoryReq) returns (CategoryData);
    rpc GetCategories(GetCategoriesReq) returns (CategoriesPage);
}

message CreateCategoryReq {
    string name = 1;
}

message CategoryData {
    int64 id = 1;
    string name = 2;
}

message GetCategoriesReq {
    int32 page_number = 1;
    int32 page_size = 2;
    string search_token = 3;
}

message CategoriesPage {
    repeated CategoryData categories = 1;
    int64 total_count = 2;
}