syntax = "proto3";

package tracks;

service Tracks {
    rpc GetFullTrack(GetTrackReq) returns (FullTrack);
    rpc UploadTrack(UploadTrackReq) returns (TrackId);
    rpc UpdateTrack(UpdateTrackReq) returns (Empty);
    rpc UpdateTrackThumbnail(UpdateTrackThumbnailReq) returns (Empty);
    rpc RemoveTrack(RemoveTrackReq) returns (Empty);
    rpc LinkTrackAudio(LinkTrackAudioReq) returns (Empty);
    rpc GeneratePlayToken(GeneratePlayTokenReq) returns (PlayToken);
}

message Empty {}

message GetTrackReq {
    int64 track_id = 1;
}

message UploadTrackReq {
    string title = 1;
    optional string description = 2;
    int64 uploader_id = 3;
    repeated int64 categories_ids = 4;
}

message UpdateTrackReq {
    int64 track_id = 1;
    string title = 2;
    optional string description = 3;
    repeated int64 categories_ids = 4;
    int64 uploader_id = 5;
}

message Image {
    bytes image = 1;
    string mime_type = 2;
}

message UpdateTrackThumbnailReq {
    int64 track_id = 1;
    optional Image thumbnail = 2;
    int64 uploader_id = 3;
}

message RemoveTrackReq {
    int64 track_id = 1;
    int64 uploader_id = 2;
}

message LinkTrackAudioReq {
    int64 track_id = 1;
    string audio_uri = 2;
    int64 duration_seconds = 3;
    int64 uploader_id = 4;
}

message GeneratePlayTokenReq {
    int64 track_id = 1;
}

message FullTrack {
    int64 id = 1;
    string title = 2;
    optional string description = 3;
    optional string thumbnail_id = 4;
    optional int64 duration_seconds = 5;
    int64 play_count = 6;
    int64 like_count = 7;
    int64 uploader_id = 8;
    repeated Category categories = 9;
}

message TrackId {
    int64 id = 1;
}

message PlayToken {
    string play_token = 1;
}

message Category {
    int64 id = 1;
    string name = 2;
}