name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Prelude
        run: |
          PROTOC_VERSION=$(curl -s "https://api.github.com/repos/protocolbuffers/protobuf/releases/latest" | grep -Po '"tag_name": "v\K[0-9.]+')
          wget -qO protoc.zip https://github.com/protocolbuffers/protobuf/releases/latest/download/protoc-$PROTOC_VERSION-linux-x86_64.zip
          sudo unzip -q protoc.zip bin/protoc -d /usr/local
          sudo chmod a+x /usr/local/bin/protoc
          rm -rf protoc.zip
      - name: Set rust toolchain
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Set env
        run: echo "SQLX_OFFLINE=true" >> $GITHUB_ENV
      - name: Build project
        run: cargo test
      - name: Run unit tests
        run: cargo test